//! # adbc-spanner
//!
//! An [ADBC](https://arrow.apache.org/adbc/) (Arrow Database Connectivity) driver for
//! [Google Cloud Spanner](https://cloud.google.com/spanner), built on top of the official
//! `google-cloud-spanner` preview client and the native Rust [`adbc_core`] traits.
//!
//! The driver exposes Spanner through the standard ADBC object hierarchy:
//!
//! ```text
//! SpannerDriver ──> SpannerDatabase ──> SpannerConnection ──> SpannerStatement
//! ```
//!
//! Query results are returned as Arrow [`RecordBatch`](arrow_array::RecordBatch)es, so they can be
//! consumed by any Arrow-native tool without an intermediate row-by-row copy.
//!
//! ## Configuration
//!
//! The complete reference of every option at every level — with exact types, defaults, and
//! `get_option` round-trip behaviour — is
//! [docs/options.md](https://github.com/fornwall/adbc-spanner/blob/main/docs/options.md).
//!
//! A database is configured through ADBC options. The Spanner database path is required and can be
//! supplied either through the standard [`OptionDatabase::Uri`](adbc_core::options::OptionDatabase::Uri)
//! option or the driver-specific [`OPTION_DATABASE`] key:
//!
//! ```text
//! projects/<project>/instances/<instance>/databases/<database>
//! ```
//!
//! or as a **connection URI** with the `spanner:` scheme, whose query parameters are
//! database-level driver options and whose optional `//host:port` authority becomes
//! [`OPTION_ENDPOINT`]:
//!
//! ```text
//! spanner:///projects/<p>/instances/<i>/databases/<d>?spanner.endpoint=http://localhost:9010&spanner.emulator=true
//! ```
//!
//! A URI is expanded into the individual options at the moment it is set, so ordering is
//! deterministic: an option set after the URI wins, and the URI overwrites only the fields it
//! actually carries. Unknown query keys are rejected; values are percent-decoded (RFC 3986).
//! `get_option("uri")` returns the stored database path, not the original URI.
//!
//! To talk to a Spanner emulator, either set the `SPANNER_EMULATOR_HOST` environment variable (the
//! driver picks it up automatically and uses anonymous credentials) or set the [`OPTION_ENDPOINT`]
//! and [`OPTION_EMULATOR`] options explicitly.
//!
//! The standard `adbc.connection.readonly`
//! ([`OptionConnection::ReadOnly`](adbc_core::options::OptionConnection::ReadOnly)) connection
//! option opens a **read-only** connection: when set to `true` the connection rejects all writes —
//! DML, DDL and bulk ingest fail with [`Status::InvalidState`](adbc_core::error::Status::InvalidState),
//! while read-only queries still run. It defaults to `false`, accepts `true`/`false`, and
//! round-trips through `get_option`. The flag is live: statements check it at execution time, so
//! toggling it takes effect immediately for existing statements as well as new ones.
//!
//! ## Transactions
//!
//! Connections are in **autocommit** mode by default. Setting `adbc.connection.autocommit` to
//! `false` enters manual transaction mode, in which DML — and any bulk ingest's insert mutations —
//! is **buffered** and applied atomically in
//! one read/write transaction on `commit` (the Spanner client exposes read/write transactions only
//! through a closure-based runner, so there is no true open transaction to run statements in).
//! Two consequences: a manual transaction has **no read-your-writes** — queries run immediately in
//! a fresh read-only snapshot and do not see buffered DML, so an `INSERT` followed by a
//! `SELECT COUNT(*)` returns the pre-insert count — and DDL issued after buffered DML **executes
//! before it** (DDL runs immediately; it is never transactional in Spanner). See
//! [`SpannerConnection`] for the full model.
//!
//! ## Example
//!
//! ```no_run
//! use adbc_core::{Driver, Database, Connection, Statement};
//! use adbc_core::options::{OptionDatabase, OptionValue};
//! use adbc_spanner::{SpannerDriver, OPTION_DATABASE};
//! use arrow_array::RecordBatchReader;
//!
//! # fn main() -> adbc_core::error::Result<()> {
//! let mut driver = SpannerDriver::try_new()?;
//! let database = driver.new_database_with_opts([(
//!     OptionDatabase::Other(OPTION_DATABASE.into()),
//!     OptionValue::String("projects/p/instances/i/databases/d".into()),
//! )])?;
//! let mut connection = database.new_connection()?;
//! let mut statement = connection.new_statement()?;
//! statement.set_sql_query("SELECT 1 AS one")?;
//! let reader = statement.execute()?;
//! for batch in reader {
//!     let batch = batch?;
//!     println!("got {} rows", batch.num_rows());
//! }
//! # Ok(())
//! # }
//! ```

// `missing_docs`, `missing_debug_implementations`, `unreachable_pub` and `unsafe_op_in_unsafe_fn`
// are configured in `[lints.rust]` in Cargo.toml (they apply uniformly to all targets). The two
// `unsafe_code` lints below stay here because they are feature-conditional.
//
// No hand-written `unsafe` anywhere in this crate. The only unsafe is the C-ABI entrypoint
// generated by `adbc_ffi::export_driver!` in the `ffi` module, which carries a single audited
// `#[allow(unsafe_code)]`. Deny elsewhere so new unsafe can't creep in, and hard-`forbid` it
// entirely in the pure-Rust build (no `ffi` feature), where no unsafe exists at all.
#![deny(unsafe_code)]
#![cfg_attr(not(feature = "ffi"), forbid(unsafe_code))]

mod bind;
mod connection;
mod conversion;
mod directed_read;
mod driver;
mod error;
#[cfg(feature = "ffi")]
#[allow(unsafe_code)] // `export_driver!` generates the C-ABI `unsafe extern "C"` entrypoints.
mod ffi;
mod info;
mod nested;
mod objects;
mod options;
mod query_options;
mod request;
mod retry;
mod runtime;
mod sql;
mod staleness;
mod statement;
mod statistics;
mod timeout;

pub use connection::SpannerConnection;
pub use driver::{SpannerDatabase, SpannerDriver};
pub use statement::SpannerStatement;

/// Internal parsing helpers exposed for fuzz targets only (enable the `fuzzing` feature).
///
/// **Not** part of the public API — no stability guarantees.
#[cfg(feature = "fuzzing")]
#[doc(hidden)]
pub mod fuzzing {
    /// Split a `;`-separated SQL batch into individual statements (quote/comment aware).
    pub fn split_statements(sql: &str) -> Vec<String> {
        crate::sql::split_statements(sql)
    }
    /// Whether the SQL begins with a DDL statement.
    pub fn is_ddl(sql: &str) -> bool {
        crate::sql::is_ddl(sql)
    }
    /// Whether the SQL contains a top-level `THEN RETURN` clause.
    pub fn is_dml_returning(sql: &str) -> bool {
        crate::sql::is_dml_returning(sql)
    }
    /// Parse a Spanner `DATE` string into Arrow `Date32` days.
    pub fn parse_date_days(s: &str) -> Option<i32> {
        crate::conversion::parse_date_days(s)
    }
    /// Parse a Spanner `TIMESTAMP` string into epoch nanoseconds.
    pub fn parse_timestamp_nanos(s: &str) -> Option<i64> {
        crate::conversion::parse_timestamp_nanos(s)
    }
    /// Parse a Spanner `NUMERIC` string into an unscaled `i128` (scale 9).
    pub fn parse_numeric_i128(s: &str) -> Option<i128> {
        crate::conversion::parse_numeric_i128(s)
    }
    /// Match an ADBC `LIKE` pattern against a value.
    pub fn like_match(pattern: &str, value: &str) -> bool {
        crate::connection::like_match(pattern, value)
    }
    /// The first SQL keyword, uppercased — skipping whitespace, comments, and `@{…}` statement
    /// hints.
    pub fn first_keyword(sql: &str) -> Option<String> {
        crate::sql::first_keyword(sql)
    }
    /// Whether the SQL begins with a DML statement (`INSERT`/`UPDATE`/`DELETE`).
    pub fn is_dml(sql: &str) -> bool {
        crate::sql::is_dml(sql)
    }
    /// Strip trailing top-level `;` terminators from a single-statement query.
    pub fn strip_trailing_terminators(sql: &str) -> String {
        crate::sql::strip_trailing_terminators(sql)
    }
    /// The distinct `@name` bind parameters of a query, in first-appearance order.
    pub fn named_parameters(sql: &str) -> Vec<String> {
        crate::sql::named_parameters(sql)
    }
    /// Backtick-quote a Spanner identifier (GoogleSQL backslash escaping).
    pub fn quote_ident(ident: &str) -> String {
        crate::sql::quote_ident(ident)
    }
    /// Resolve the column→parameter pairing for `sql` against a batch whose columns are named
    /// `column_names` (built here as nullable `Int64`; the pairing never looks at types), under the
    /// given `bind_by_name` mode (`adbc.statement.bind_by_name`: `false` positional, `true`
    /// by-name).
    ///
    /// Returns the resolved names, or `None` on a documented rejection — after asserting the error
    /// is `InvalidArguments` (any other status, like any panic, is a bug).
    pub fn resolve_parameter_names(
        sql: &str,
        column_names: &[String],
        bind_by_name: bool,
    ) -> Option<Vec<String>> {
        use arrow_array::RecordBatch;
        use arrow_schema::{DataType, Field, Schema};
        let fields: Vec<Field> = column_names
            .iter()
            .map(|name| Field::new(name, DataType::Int64, true))
            .collect();
        let batch = RecordBatch::new_empty(std::sync::Arc::new(Schema::new(fields)));
        match crate::bind::resolve_parameter_names(sql, &batch, bind_by_name) {
            Ok(names) => Some(names),
            Err(e) => {
                assert_eq!(
                    e.status,
                    adbc_core::error::Status::InvalidArguments,
                    "resolve_parameter_names must reject with InvalidArguments: {e:?}"
                );
                None
            }
        }
    }
    /// Decode an opaque partition descriptor, returning whether it decoded.
    ///
    /// The oracles live here (where the client's `Partition` type is in scope): a rejected
    /// descriptor must be a clean `InvalidArguments` error — never a panic — and an accepted one
    /// must reach a byte-stable fixed point under the driver's own encoder: from a canonical
    /// descriptor, decode → encode → decode → encode reproduces the enveloped bytes exactly.
    ///
    /// The fixed point is asserted from `encode_partition`'s *own* output, not from the arbitrary
    /// input's first encode. A hand-crafted descriptor can carry a value whose lexical form serde
    /// does not preserve — most notably a huge integer literal, which overflows `i64`/`u64` and is
    /// parsed to `f64` by an imprecise path, so its first re-encode (a canonical ryu float) decodes
    /// back to a *different* `f64` than the encoder emitted. One normalization pass reaches the
    /// fixed point; every real descriptor `encode_partition` produces is already there (it only ever
    /// emits ryu floats), so this does not weaken the invariant that matters for `read_partition`.
    pub fn decode_partition(descriptor: &[u8]) -> bool {
        match crate::connection::decode_partition(descriptor) {
            Ok(partition) => {
                use crate::connection::{decode_partition, encode_partition};
                // Normalize once so the comparison starts from a canonical encoder output, then
                // assert the round-trip from there is byte-stable.
                let first = encode_partition(&partition).expect("a decoded partition re-encodes");
                let normalized =
                    decode_partition(&first).expect("a re-encoded partition descriptor decodes");
                let bytes = encode_partition(&normalized).expect("a decoded partition re-encodes");
                let again =
                    decode_partition(&bytes).expect("a re-encoded partition descriptor decodes");
                assert_eq!(
                    bytes,
                    encode_partition(&again).expect("a decoded partition re-encodes"),
                    "enveloped partition descriptor round-trip changed the bytes"
                );
                true
            }
            Err(e) => {
                assert_eq!(
                    e.status,
                    adbc_core::error::Status::InvalidArguments,
                    "decode_partition must reject with InvalidArguments: {e:?}"
                );
                assert!(
                    e.message.contains("invalid partition descriptor")
                        || e.message.contains("not supported by this driver"),
                    "unexpected rejection message: {}",
                    e.message
                );
                false
            }
        }
    }
    /// Normalize an emulator endpoint by adding an `http://` scheme when absent.
    pub fn ensure_scheme(host: &str) -> String {
        crate::driver::ensure_scheme(host)
    }

    /// An arbitrary ADBC option value, mirroring the variants of
    /// [`OptionValue`](adbc_core::options::OptionValue) the driver accepts.
    #[derive(arbitrary::Arbitrary, Debug)]
    pub enum OptValue {
        Str(String),
        Int(i64),
        Double(f64),
        Bytes(Vec<u8>),
    }

    /// Drive the database option-handling code (`set_option` / `get_option_string`) with arbitrary
    /// key/value pairs, exactly as the C ABI would after a driver manager forwards untrusted option
    /// strings. Exercises the string/bool/int coercions and the unknown-key error path; must never
    /// panic. No network I/O — this stops well before `connect()`.
    ///
    /// The `SpannerDriver` (and its shared Tokio runtime) is built once and reused across calls so
    /// fuzzing throughput is not dominated by runtime construction.
    pub fn exercise_database_options(ops: Vec<(String, OptValue)>) {
        use adbc_core::options::{OptionDatabase, OptionValue};
        use adbc_core::{Driver, Optionable};
        use std::sync::{Mutex, OnceLock};

        static DRIVER: OnceLock<Mutex<crate::SpannerDriver>> = OnceLock::new();
        let driver = DRIVER.get_or_init(|| {
            Mutex::new(crate::SpannerDriver::try_new().expect("driver construction is infallible"))
        });

        let mut database = {
            let mut guard = driver.lock().unwrap();
            match guard.new_database() {
                Ok(db) => db,
                Err(_) => return,
            }
        };

        for (key, value) in ops {
            let value = match value {
                OptValue::Str(s) => OptionValue::String(s),
                OptValue::Int(i) => OptionValue::Int(i),
                OptValue::Double(d) => OptionValue::Double(d),
                OptValue::Bytes(b) => OptionValue::Bytes(b),
            };
            // Both known driver options and arbitrary unknown keys go through `Other`; errors
            // (unsupported key, wrong value type, non-boolean text) are expected, not panics.
            let _ = database.set_option(OptionDatabase::Other(key.clone()), value);
            let _ = database.get_option_string(OptionDatabase::Other(key));
        }
    }

    #[cfg(test)]
    mod tests {
        /// Run the partition-descriptor oracle over the checked-in fuzz seed corpus
        /// (`fuzz/seeds/partition/`), so a corpus/oracle mismatch fails `cargo test
        /// --features fuzzing` locally instead of only surfacing in a fuzz run. The enveloped
        /// seed must be accepted; the bad-version seed must be rejected — both verdicts include
        /// the oracle's internal round-trip and clean-rejection assertions.
        #[test]
        fn partition_seed_corpus_satisfies_the_oracle() {
            let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("fuzz/seeds/partition");
            let mut verdicts = std::collections::BTreeMap::new();
            for entry in std::fs::read_dir(dir).expect("seed corpus directory exists") {
                let path = entry.unwrap().path();
                let bytes = std::fs::read(&path).unwrap();
                let name = path.file_name().unwrap().to_str().unwrap().to_string();
                verdicts.insert(name, super::decode_partition(&bytes));
            }
            let expected: std::collections::BTreeMap<String, bool> = [
                ("enveloped-bad-version", false),
                ("enveloped-query-descriptor", true),
            ]
            .into_iter()
            .map(|(name, accepted)| (name.to_string(), accepted))
            .collect();
            assert_eq!(verdicts, expected);
        }
    }
}

/// Internal conversion entry point exposed only for the criterion benchmarks in `benches/`
/// (a bench target can only reach the crate's public API).
///
/// **Not** part of the public API — no stability guarantees.
#[doc(hidden)]
pub mod bench_support {
    use arrow_array::ArrayRef;
    use arrow_schema::DataType;
    use google_cloud_spanner::value::Value;

    /// Build an Arrow array of `data_type` from one Spanner wire [`Value`] per row — the core of
    /// the row→Arrow conversion that `execute` performs for every streamed chunk.
    pub fn build_array(
        data_type: &DataType,
        values: &[Option<&Value>],
    ) -> adbc_core::error::Result<ArrayRef> {
        crate::conversion::build_array(data_type, values)
    }
}

/// Driver-specific database option: the fully-qualified Spanner database path,
/// `projects/<project>/instances/<instance>/databases/<database>`, or a `spanner:` **connection
/// URI** carrying that path plus database-level options as query parameters (see the
/// [crate-level Configuration docs](crate#configuration)).
///
/// Equivalent to setting [`OptionDatabase::Uri`](adbc_core::options::OptionDatabase::Uri).
pub const OPTION_DATABASE: &str = "spanner.database";

/// Driver-specific database option: an explicit gRPC endpoint (for example the address of a
/// Spanner emulator, `http://localhost:9010`). When unset the client connects to the production
/// Spanner service.
pub const OPTION_ENDPOINT: &str = "spanner.endpoint";

/// Driver-specific database option: when set to `true`, connect with anonymous credentials
/// (the mode used by the Spanner emulator). Automatically enabled when `SPANNER_EMULATOR_HOST`
/// is present in the environment. Combining emulator mode with explicitly configured credentials
/// ([`OPTION_KEYFILE`], [`OPTION_KEYFILE_JSON`], [`OPTION_IMPERSONATE_TARGET_PRINCIPAL`], or
/// [`OPTION_ACCESS_TOKEN`]) is refused at connect time instead of silently ignoring them.
pub const OPTION_EMULATOR: &str = "spanner.emulator";

/// Driver-specific database option: path to a service-account JSON key file to authenticate with
/// (dbt's `keyfile`). Overridden by [`OPTION_KEYFILE_JSON`] if both are set.
pub const OPTION_KEYFILE: &str = "spanner.keyfile";

/// Driver-specific database option: an inline service-account JSON key (dbt's `keyfile_json`).
///
/// When neither this nor [`OPTION_KEYFILE`] is set (and not connecting to an emulator), the driver
/// falls back to Application Default Credentials.
pub const OPTION_KEYFILE_JSON: &str = "spanner.keyfile_json";

/// Driver-specific database option: the service-account email to impersonate. Setting this **enables
/// service-account impersonation** — the base credentials (ADC, keyfile, …) are used to mint a
/// short-lived access token for this target principal via the IAM Credentials
/// `generateAccessToken` API, and the driver authenticates as the target. When unset, no
/// impersonation happens and authentication is unchanged.
///
/// Follows gcloud's `--impersonate-service-account` / `google-cloud-auth`'s `impersonated` builder.
pub const OPTION_IMPERSONATE_TARGET_PRINCIPAL: &str = "spanner.impersonate.target_principal";

/// Driver-specific database option: an optional delegation chain for impersonation — a
/// comma-separated list of service-account emails, each of which must have the *Token Creator* role
/// on the next, with the last granting it on [`OPTION_IMPERSONATE_TARGET_PRINCIPAL`]. Only used when
/// a target principal is set. Follows gcloud's `--impersonate-service-account` delegation chain.
pub const OPTION_IMPERSONATE_DELEGATES: &str = "spanner.impersonate.delegates";

/// Driver-specific database option: optional OAuth 2.0 scopes for the impersonated token, as a
/// comma-separated list. Defaults to the `cloud-platform` scope when unset. Only used when a target
/// principal is set. Follows the `google-cloud-auth` `impersonated` builder's `scopes`.
pub const OPTION_IMPERSONATE_SCOPES: &str = "spanner.impersonate.scopes";

/// Driver-specific database option: the lifetime (in seconds) of the impersonated access token.
/// Defaults to 3600 (one hour) when unset. Only used when a target principal is set. Follows the
/// `google-cloud-auth` `impersonated` builder's `lifetime` (and gcloud's `--lifetime`).
pub const OPTION_IMPERSONATE_LIFETIME: &str = "spanner.impersonate.lifetime";

/// Driver-specific database option: a caller-supplied OAuth 2.0 access token (a bearer token) to
/// authenticate with directly.
///
/// When set, the driver sends the token verbatim as the `Authorization: Bearer <token>` header on
/// every request and performs **no refresh** — the caller is responsible for supplying a valid,
/// unexpired token. This is useful when a token has already been obtained out of band (for example
/// via `gcloud auth print-access-token`, a Workload Identity exchange, or another auth library).
///
/// It is a complete credential in its own right and is therefore **mutually exclusive** with
/// [`OPTION_KEYFILE`], [`OPTION_KEYFILE_JSON`], and [`OPTION_IMPERSONATE_TARGET_PRINCIPAL`]:
/// combining it with any of them is refused at connect time with
/// [`Status::InvalidState`](adbc_core::error::Status::InvalidState). Like the keyfile options, it
/// also conflicts with emulator mode (which forces anonymous credentials).
pub const OPTION_ACCESS_TOKEN: &str = "spanner.access_token";

/// Driver-specific statement option: the number of rows converted into each Arrow
/// [`RecordBatch`](arrow_array::RecordBatch) streamed by
/// [`Statement::execute`](adbc_core::Statement::execute). Larger batches trade memory for fewer
/// per-batch conversions; smaller batches lower first-batch latency and peak memory. Accepts a
/// positive integer (via `set_option`/`set_option_int`); defaults to 8192.
pub const OPTION_ROWS_PER_BATCH: &str = "spanner.rows_per_batch";

/// Driver-specific statement option: enable **Data Boost** for
/// [`Statement::execute_partitions`](adbc_core::Statement::execute_partitions). When `true`, each
/// partition executes on Spanner's serverless, workload-isolated compute (independent of the
/// provisioned instance). The flag is baked into every partition descriptor, so a partition read
/// back with [`Connection::read_partition`](adbc_core::Connection::read_partition) — on any
/// connection or worker — honours it. Accepts a boolean; defaults to `false`.
pub const OPTION_DATA_BOOST: &str = "spanner.data_boost_enabled";

/// Driver-specific statement option: the maximum number of partitions to request from
/// [`Statement::execute_partitions`](adbc_core::Statement::execute_partitions). This is a hint —
/// Spanner may return fewer. Accepts a positive integer; unset lets Spanner choose.
pub const OPTION_MAX_PARTITIONS: &str = "spanner.max_partitions";

/// Statement option controlling how bound Arrow columns pair with the query's `@name` parameters,
/// following the ADBC SQLite reference driver's `bind_by_name` convention
/// ([apache/arrow-adbc#3362](https://github.com/apache/arrow-adbc/issues/3362)). A boolean,
/// defaulting to `false`:
///
/// - **`false`** (the default): strictly positional. The *i*-th bound column binds to the *i*-th
///   distinct `@name` parameter in query order; column names are ignored entirely. This is the
///   ADBC ordinal contract that positional clients (PostgreSQL/Snowflake-style drivers, the Python
///   DBAPI, validation suites) rely on.
/// - **`true`**: strict by-name. Each column binds to `@<its own name>` (order-independent); a
///   bound column that names no query parameter fails with `InvalidArguments` naming the missing
///   parameter. Use this when the bound column names are authoritative and may not match the
///   parameters' textual order.
///
/// Accepts a boolean. `get_option` reports `true`/`false`.
pub const OPTION_BIND_BY_NAME: &str = "adbc.statement.bind_by_name";

/// Driver-specific statement option: the **primary key** for a `create`/`create_append`/`replace`
/// bulk ingest.
///
/// Spanner requires every table to have a primary key, but Arrow ingest data carries none, so by
/// default the create modes append a hidden `adbc_ingest_key` UUID column and key on it. Set this
/// option to one or more **existing** ingest columns (comma-separated for a composite key) to key on
/// them instead — no synthetic column is added, and the column order given becomes the key order
/// (which governs Spanner's physical row layout). Every named column must appear in the bound ingest
/// data, else the create fails with `InvalidArguments`; Spanner additionally rejects key columns of
/// unsupported types (e.g. `FLOAT64`, `JSON`, `ARRAY`). Only affects the table-creating modes —
/// `append` ingests into an existing table whose own key governs.
///
/// A free-form string; `""` (or all-whitespace) unsets, back to the synthetic key. When set,
/// `get_option` reports the comma-joined column list; when unset it reports `NotFound`, like the
/// driver's other unset string options.
pub const OPTION_INGEST_PRIMARY_KEY: &str = "spanner.ingest.primary_key";

/// Driver-specific connection **and** statement option: the **read staleness** for read-only
/// queries, as `"exact:<duration>"` or `"max:<duration>"`.
///
/// - `exact:<duration>` reads exactly `<duration>` in the past
///   ([`TimestampBound::exact_staleness`](https://docs.cloud.google.com/spanner/docs/timestamp-bounds#exact_staleness)) —
///   a single, repeatable timestamp, cheaper and lock-free.
/// - `max:<duration>` reads at any timestamp within `<duration>` of now (bounded staleness; the
///   server picks — single-use reads only).
///
/// `<duration>` is a non-negative number with an optional unit suffix: `s` (seconds, the default),
/// `ms`, `us`/`µs`, `ns`, `m` (minutes) or `h` (hours). Examples: `exact:10`, `exact:2.5s`,
/// `max:500ms`, `max:1m`.
///
/// Mutually exclusive with [`OPTION_READ_TIMESTAMP`]; set the other to an empty string to unset it.
/// Set on a connection it becomes the default for statements it creates; a statement may override
/// it. Unset (the default) means a **strong** read.
pub const OPTION_READ_STALENESS: &str = "spanner.read.staleness";

/// Driver-specific connection **and** statement option: an **absolute read timestamp** for
/// read-only queries — an RFC 3339 timestamp, optionally prefixed to select the mode:
///
/// - `read:<rfc3339>` (or a bare `<rfc3339>`) reads exactly as of that timestamp
///   ([`TimestampBound::read_timestamp`](https://docs.cloud.google.com/spanner/docs/timestamp-bounds#exact_staleness)).
/// - `min:<rfc3339>` reads at that timestamp or later (bounded staleness; single-use reads only).
///
/// Examples: `2026-07-07T00:00:00Z`, `read:2026-07-07T00:00:00Z`, `min:2026-07-07T00:00:00+02:00`.
///
/// Mutually exclusive with [`OPTION_READ_STALENESS`]; set the other to an empty string to unset it.
/// Set on a connection it becomes the default for statements it creates; a statement may override
/// it. Unset (the default) means a **strong** read.
pub const OPTION_READ_TIMESTAMP: &str = "spanner.read.timestamp";

/// Driver-specific connection **and** statement option: the **request priority** Spanner's
/// scheduler uses to arbitrate CPU between workloads — `low`, `medium` or `high`
/// (case-insensitive). Applied to every query and DML statement the driver builds, and as the
/// **commit priority** of every read/write transaction runner (autocommit DML, the manual-mode
/// commit, ingest commits). Unset (the default) leaves the service default (high); set an empty
/// string to unset. Set on a connection it becomes the default for statements it creates; a
/// statement may override it. Driver-internal metadata queries (`get_objects`, schema probes, …)
/// are not affected.
///
/// Modeled on the BigQuery ADBC driver's `bigquery.query.priority` option; see Spanner's
/// [`RequestOptions.priority`](https://docs.cloud.google.com/spanner/docs/reference/rest/v1/RequestOptions).
pub const OPTION_REQUEST_PRIORITY: &str = "spanner.request.priority";

/// Driver-specific connection **and** statement option: a
/// [directed read](https://docs.cloud.google.com/spanner/docs/directed-reads) replica selection for
/// read-only queries, steering where a read is served. The value is a small grammar:
///
/// ```text
/// <mode> [ ":" <selection> ("," <selection>)* ] [ ";auto_failover_disabled" ]
/// ```
///
/// - `<mode>` is `include` (an ordered preference list Spanner tries in turn) or `exclude`
///   (replicas Spanner routes around), case-insensitive.
/// - Each `<selection>` is `<location>`, `<location>:<type>` or `:<type>` (at least one of the two),
///   where `<location>` is a region such as `us-east1` and `<type>` is `read_write`, `read_only` or
///   `any` (case-insensitive; `any`/omitted matches every replica type).
/// - The optional `;auto_failover_disabled` suffix (valid only with `include`) stops Spanner from
///   falling back to a replica outside the list when the listed replicas are unavailable.
///
/// Examples: `include:us-east1`, `include:us-east1:read_only,us-east4:read_write`,
/// `exclude:us-central1`, `include:us-east1;auto_failover_disabled`.
///
/// Directed reads apply to **read-only queries only** — Spanner rejects them on a read/write
/// transaction — so the option is honoured on the driver's query paths (autocommit and manual mode
/// alike, including parameterized/bound queries and `execute_partitions`) and ignored by DML/DDL.
/// Unset by default (Spanner's own routing); set an empty string to unset. Malformed values fail
/// with `InvalidArguments`. Set on a connection it becomes the default for statements it creates; a
/// statement may override it. Round-trips through `get_option` (the raw, trimmed value).
pub const OPTION_DIRECTED_READ: &str = "spanner.directed_read";

/// Driver-specific connection **and** statement option: a free-form **request tag**, attached to
/// every query/DML statement (and `ExecuteBatchDml` batch) the driver builds and surfaced in
/// Spanner's query and transaction statistics for
/// [troubleshooting with tags](https://docs.cloud.google.com/spanner/docs/introspection/troubleshooting-with-tags).
/// Unset by default; set an empty string to unset. Set on a connection it becomes the default for
/// statements it creates; a statement may override it.
pub const OPTION_REQUEST_TAG: &str = "spanner.request.tag";

/// Driver-specific connection **and** statement option: the query **optimizer version** Spanner
/// uses to plan queries — a version string such as `"6"` or `"latest"`. Applied as a
/// [`QueryOptions`](https://docs.cloud.google.com/spanner/docs/reference/rest/v1/ExecuteSqlRequest#queryoptions)
/// on every query statement the driver builds. The value is opaque (passed to Spanner unchanged);
/// unset (the default) leaves the database/service default optimizer. Set an empty string to unset.
/// Set on a connection it becomes the default for statements it creates; a statement may override
/// it. See Spanner's
/// [query optimizer versions](https://docs.cloud.google.com/spanner/docs/query-optimizer/manage-query-optimizer).
pub const OPTION_QUERY_OPTIMIZER_VERSION: &str = "spanner.query.optimizer_version";

/// Driver-specific connection **and** statement option: the query **optimizer statistics package**
/// Spanner plans against — a named statistics package. Applied as a
/// [`QueryOptions`](https://docs.cloud.google.com/spanner/docs/reference/rest/v1/ExecuteSqlRequest#queryoptions)
/// on every query statement the driver builds. The value is opaque (passed to Spanner unchanged);
/// unset (the default) leaves the database default. Value handling and connection→statement
/// inheritance are as [`OPTION_QUERY_OPTIMIZER_VERSION`]. See Spanner's
/// [optimizer statistics packages](https://docs.cloud.google.com/spanner/docs/query-optimizer/statistics-packages).
pub const OPTION_QUERY_OPTIMIZER_STATISTICS_PACKAGE: &str =
    "spanner.query.optimizer_statistics_package";

/// Driver-specific connection **and** statement option: the **query timeout**, in seconds — an
/// overall deadline on the *initial execution* of a query: the `ExecuteStreamingSql` call plus the
/// first chunk of a streamed result, the `execute_schema` / `execute_partitions` probes, and the
/// initial fetch of [`Connection::read_partition`](adbc_core::Connection::read_partition).
/// Subsequent chunk fetches of a streamed result are bounded by [`OPTION_RPC_TIMEOUT_FETCH`]
/// instead. An expired deadline fails with [`Status::Timeout`](adbc_core::error::Status::Timeout).
///
/// The value is a finite, non-negative number of seconds (fractions allowed; `NaN`/infinities are
/// rejected), accepted as a numeric string, an integer, or a double; it round-trips through
/// `get_option` and `get_option_double`. `0` disables the timeout; an empty string unsets it.
/// Unset (the default) means no deadline. Set on a connection it becomes the default for
/// statements it creates; a statement may override it. It also bounds the driver-internal metadata
/// **read** queries (`get_objects`, `get_statistics`, `get_table_schema`, the ingest table-exists
/// probe), which are executions of a query. Naming parallels the Flight SQL ADBC driver's
/// `adbc.flight.sql.rpc.timeout_seconds.*` options; the full semantics are in
/// [docs/options.md](https://github.com/fornwall/adbc-spanner/blob/main/docs/options.md#rpc-timeouts).
pub const OPTION_RPC_TIMEOUT_QUERY: &str = "spanner.rpc.timeout_seconds.query";

/// Driver-specific connection **and** statement option: the **update timeout**, in seconds — an
/// overall deadline on each write operation: an autocommit DML / batch-DML read/write transaction,
/// the manual-mode commit (including re-enabling autocommit, which commits the buffer), each
/// bulk-ingest commit chunk, and a DDL change — the admin `UpdateDatabaseDdl` call **and** its
/// long-running-operation poll loop (which otherwise polls without any bound). The deadline covers
/// the whole driver-side operation, including any retries the client performs within it. An expired
/// deadline fails with [`Status::Timeout`](adbc_core::error::Status::Timeout) — note Spanner may
/// still have committed a transaction whose confirmation the driver stopped waiting for, the usual
/// ambiguity of any timed-out commit.
///
/// Value syntax, validation, `0`/`""` handling, round-trip and inheritance are as
/// [`OPTION_RPC_TIMEOUT_QUERY`].
pub const OPTION_RPC_TIMEOUT_UPDATE: &str = "spanner.rpc.timeout_seconds.update";

/// Driver-specific connection **and** statement option: the **fetch timeout**, in seconds — an
/// overall deadline on *each subsequent chunk fetch* of a streamed result (after the first chunk,
/// which [`OPTION_RPC_TIMEOUT_QUERY`] covers), enforced inside the background prefetch task so a
/// stalled stream fails the consumer's next batch with
/// [`Status::Timeout`](adbc_core::error::Status::Timeout) instead of hanging. For a bound
/// (parameterized) query over several rows it also covers executing each per-row statement as the
/// stream advances.
///
/// Value syntax, validation, `0`/`""` handling, round-trip and inheritance are as
/// [`OPTION_RPC_TIMEOUT_QUERY`].
pub const OPTION_RPC_TIMEOUT_FETCH: &str = "spanner.rpc.timeout_seconds.fetch";

/// Driver-specific connection **and** statement option: the **maximum number of attempts** the
/// Spanner client makes for a retryable RPC — the first try plus retries — as a positive integer.
/// `1` disables retrying; unset (the default) leaves the client's own policy, which has no attempt
/// cap.
///
/// The value is accepted as an integer, a whole-valued double, or a numeric string, and round-trips
/// through `get_option` and `get_option_int`. An empty string unsets it. Setting it (or
/// [`OPTION_RETRY_MAX_ELAPSED_SECONDS`], or both) bounds the client's default retry policy while
/// preserving its transport-error-on-idempotent retrying; the two limits combine (the retry loop
/// stops at whichever is reached first). Set on a connection it becomes the default for statements
/// it creates; a statement may override it. This tunes the *per-attempt* retry loop; the separate
/// [`OPTION_RPC_TIMEOUT_QUERY`] family bounds the *overall* per-operation wall time.
///
/// Mirrors the gax `RetryPolicyExt::with_attempt_limit` knob.
pub const OPTION_RETRY_MAX_ATTEMPTS: &str = "spanner.retry.max_attempts";

/// Driver-specific connection **and** statement option: the **maximum total wall-clock time**, in
/// seconds, the Spanner client spends retrying a retryable RPC before the last error is surfaced as
/// permanent. A finite, strictly positive number of seconds (fractions allowed); unset (the
/// default) leaves the client's own policy, which has no elapsed-time cap.
///
/// The value is accepted as a numeric string, an integer, or a double, and round-trips through
/// `get_option` and `get_option_double`. An empty string unsets it. Value handling, combination
/// with [`OPTION_RETRY_MAX_ATTEMPTS`], and connection→statement inheritance are as that option.
///
/// Mirrors the gax `RetryPolicyExt::with_time_limit` knob.
pub const OPTION_RETRY_MAX_ELAPSED_SECONDS: &str = "spanner.retry.max_elapsed_seconds";

/// Driver-specific **connection** option: a free-form **transaction tag**, applied wherever the
/// driver builds a read/write transaction (autocommit DML, the manual-mode commit, ingest commits)
/// and attached by Spanner to every operation of that transaction. Unset by default; set an empty
/// string to unset. Connection-level only (a transaction can span several statements, so there is
/// no per-statement override).
pub const OPTION_TRANSACTION_TAG: &str = "spanner.transaction.tag";

/// Driver-specific connection **and** statement option: the **maximum commit delay** Spanner may
/// add to a read/write commit so it can batch the commit with others — a throughput-for-latency
/// trade-off (see Spanner's
/// [`TransactionOptions.max_commit_delay`](https://docs.cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions)).
/// Applied at every read/write commit the driver builds: autocommit DML, the `ExecuteBatchDml`
/// batch runner, the manual-mode commit, and the bulk-ingest write-only transaction.
///
/// The value is a duration using the same grammar as [`OPTION_READ_STALENESS`] (a number, default
/// unit seconds, with optional `s`/`ms`/`us`/`ns`/`m`/`h` suffix — e.g. `100ms`, `0.2s`); it must
/// fall within Spanner's `0..=500ms` range (values outside it, and malformed values, are rejected
/// with [`Status::InvalidArguments`](adbc_core::error::Status::InvalidArguments)). `0` means no
/// delay; an empty string unsets it. Round-trips through `get_option`. Set on a connection it
/// becomes the default for statements it creates; a statement may override it.
pub const OPTION_MAX_COMMIT_DELAY: &str = "spanner.max_commit_delay";

/// Driver-specific connection **and** statement option: the maximum precision at which Spanner
/// `TIMESTAMP` columns are read into Arrow. Two values:
///
/// - `nanoseconds_error_on_overflow` (the default) — `TIMESTAMP` maps to
///   `Timestamp(Nanosecond, "UTC")`, preserving the wire value's full nanosecond precision. Arrow
///   stores nanoseconds as an `i64`, which spans only ~1677-09-21 to 2262-04-11 — narrower than
///   Spanner's 0001–9999 range — so reading a well-formed instant outside that window is a loud
///   `InvalidArguments` error naming the column and the offending value.
/// - `microseconds` — `TIMESTAMP` maps to `Timestamp(Microsecond, "UTC")`, which covers Spanner's
///   **entire** 0001–9999 range: the escape hatch for tables holding timestamps the nanosecond
///   representation cannot hold (mirroring the Snowflake ADBC driver's
///   `adbc.snowflake.sql.client_option.max_timestamp_precision`). Spanner timestamps carry up to
///   nanosecond precision on the wire, so any sub-microsecond digits are **truncated toward
///   negative infinity** in this mode.
///
/// There is deliberately no silently-wrapping nanosecond mode: a wrapped out-of-range timestamp is
/// indistinguishable from real data. The mode applies uniformly to every surface that produces
/// timestamps or timestamp-typed schemas: `execute` (including parameterized/bound queries),
/// `execute_schema` and the `execute_partitions` schema probe, `read_partition` (which uses the
/// **reading connection's** setting), DML `THEN RETURN` rows, and `get_table_schema`.
///
/// Set on a connection it becomes the default for statements it creates; a statement may override
/// it. Set an empty string to reset to the default. Round-trips through `get_option` (the
/// effective mode is always reported).
pub const OPTION_MAX_TIMESTAMP_PRECISION: &str = "spanner.max_timestamp_precision";

/// The vendor name reported by [`Connection::get_info`](adbc_core::Connection::get_info).
pub const VENDOR_NAME: &str = "Google Cloud Spanner";

/// The driver name reported by [`Connection::get_info`](adbc_core::Connection::get_info).
pub const DRIVER_NAME: &str = "adbc-spanner";

/// The version of this driver.
pub const DRIVER_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Drift guard: every option key the driver handles must be documented in `docs/options.md`.
#[cfg(test)]
mod options_doc_tests {
    #[test]
    fn every_handled_option_key_is_documented() {
        use adbc_core::constants;

        let doc = include_str!("../docs/options.md");
        let keys: &[&str] = &[
            // Driver-specific options (this crate's OPTION_* constants).
            crate::OPTION_DATABASE,
            crate::OPTION_ENDPOINT,
            crate::OPTION_EMULATOR,
            crate::OPTION_KEYFILE,
            crate::OPTION_KEYFILE_JSON,
            crate::OPTION_IMPERSONATE_TARGET_PRINCIPAL,
            crate::OPTION_IMPERSONATE_DELEGATES,
            crate::OPTION_IMPERSONATE_SCOPES,
            crate::OPTION_IMPERSONATE_LIFETIME,
            crate::OPTION_ROWS_PER_BATCH,
            crate::OPTION_DATA_BOOST,
            crate::OPTION_MAX_PARTITIONS,
            crate::OPTION_INGEST_PRIMARY_KEY,
            crate::OPTION_READ_STALENESS,
            crate::OPTION_READ_TIMESTAMP,
            crate::OPTION_REQUEST_PRIORITY,
            crate::OPTION_REQUEST_TAG,
            crate::OPTION_DIRECTED_READ,
            crate::OPTION_QUERY_OPTIMIZER_VERSION,
            crate::OPTION_QUERY_OPTIMIZER_STATISTICS_PACKAGE,
            crate::OPTION_TRANSACTION_TAG,
            crate::OPTION_MAX_COMMIT_DELAY,
            crate::OPTION_MAX_TIMESTAMP_PRECISION,
            crate::OPTION_RPC_TIMEOUT_QUERY,
            crate::OPTION_RPC_TIMEOUT_UPDATE,
            crate::OPTION_RPC_TIMEOUT_FETCH,
            crate::OPTION_RETRY_MAX_ATTEMPTS,
            crate::OPTION_RETRY_MAX_ELAPSED_SECONDS,
            // Standard ADBC (spec) options the driver handles.
            constants::ADBC_OPTION_URI,
            constants::ADBC_CONNECTION_OPTION_AUTOCOMMIT,
            constants::ADBC_CONNECTION_OPTION_READ_ONLY,
            constants::ADBC_CONNECTION_OPTION_ISOLATION_LEVEL,
            constants::ADBC_CONNECTION_OPTION_CURRENT_CATALOG,
            constants::ADBC_CONNECTION_OPTION_CURRENT_DB_SCHEMA,
            constants::ADBC_INGEST_OPTION_TARGET_TABLE,
            constants::ADBC_INGEST_OPTION_TARGET_DB_SCHEMA,
            constants::ADBC_INGEST_OPTION_TARGET_CATALOG,
            constants::ADBC_INGEST_OPTION_TEMPORARY,
            constants::ADBC_INGEST_OPTION_MODE,
        ];
        for key in keys {
            // Require the backticked form so a bare substring (e.g. "uri" inside another
            // word) cannot satisfy the check by accident.
            assert!(
                doc.contains(&format!("`{key}`")),
                "option key `{key}` is handled by the driver but missing from docs/options.md"
            );
        }
    }
}
